### ISSUE TITLE
How to pass version number from Extension Version task to Publish task

### ISSUE THREAD

**Issue by pviotti** [Microsoft/vsts-extension-build-release-tasks#113]
Is there any documented example of how to pass the updated version number resulting from executing Extension Version task to the Publish task?

I've tried setting as follows but it doesn't work

```yml
- task: ms-devlabs.vsts-developer-tools-build-tasks.extension-version-build-task.ExtensionVersion@1
  displayName: 'Query Extension Version: MyPubId.MyExtId
  inputs:
    connectedServiceName: marketplace
    publisherId: mypubid
    extensionId: myextid
    versionAction: Patch
    outputVariable: '$(Parameters.extensionVersion)'

- task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishExtension@1
  displayName: 'Publish Extension'
  inputs:
    connectedServiceName: marketplace
    extensionVersion: '$(Parameters.extensionVersion)'
```

Also, the DevOps UI looks a bit confusing - should I link the "Output Variable" or set the "Output Variables"..?

![image](https://user-images.githubusercontent.com/1350095/52645608-00efb080-2ed9-11e9-9a6b-24e97c00b222.png)
